name: Deploy Terraform State
  
on:
  workflow_dispatch:
    inputs:
      access:
        description: "AWS access key(Leave empty to use repo secret)"
        required: false
        default: ""
      secret:
        description: "AWS secret key(Leave empty to use repo secret)"
        required: false
        default: ""
      region:
        description: "AWS region"
        required: true
        default: "us-east-1"
jobs:
  terraform-apply:
    name: Terraform State Location Setup
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ github.event.inputs.access != '' && github.event.inputs.access || secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ github.event.inputs.secret != '' && github.event.inputs.secret || secrets.AWS_SECRET_KEY }}
      AWS_DEFAULT_REGION: ${{ github.event.inputs.region }}
    steps:
      - run: echo "This job is running on ${{ runner.os }} runner hosted by Github"
      - name: Repository clone 's3_state'
        uses: actions/checkout@v4
        with:
          ref: "s3_state"
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Create Bucket and Secret
        run: terraform apply -auto-approve